#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Kenzo Fujisaki
# SPDX-License-Identifier: BSD-3-Clause

x = float(input())

while True:
    Method = input()
    if Method == '+':
        y = float(input())
        x += y
    elif Method == '-':
        y = float(input())
        x -= y
    elif Method == '*':
        y = float(input())
        x *= y
    elif Method == '/':
        y = float(input())
        if y == 0:
            print("error")
            break
        else:
            x /= y
    elif Method == '=':
        print(x)
        break
    else:
        print('error')
        break